server:
  port: 8762
spring:
  application:
    name: zuul-server

eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOST:https://unir-eureka.herokuapp.com}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://unir-eureka.herokuapp.com/eureka}
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"